CREATE DATABASE IF NOT EXISTS usuarios_db;

USE usuarios_db;

CREATE TABLE IF NOT EXISTS usuarios (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  contrasena VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS registros_salientes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  valor VARCHAR(50) NOT NUL,
  ubicacion VARCHAR(50)
);
